(() => {
window.addEventListener('error', (event) => {
  const target = document.getElementById('app');
  if (target && !target.innerHTML) target.innerHTML = `<pre style="padding:24px;color:#b22">本地复刻加载错误：${String(event.error || event.message)}</pre>`;
});
const app=document.getElementById('app');
const account=document.getElementById('account');
const authDialog=document.getElementById('authDialog');
const authForm=document.getElementById('authForm');
const authMessage=document.getElementById('authMessage');
const tools=[
['01','AI出题机','从教学目标到完整试卷','按年级、学科、知识点与难度生成可编辑试卷。','teacher-efficiency'],['02','卷后提分试卷分析','从一次考试找到下次增分点','识别卷面证据，形成提分优先级与七天行动计划。','teaching-score'],['03','学习资料生成器','把教材整理成学习路径','从理解、练习到复习，生成可下载的完整学习讲义。','teacher-efficiency'],['23','教辅资料制作器','批量制作课堂教辅图','结合知识库和参考风格，生成多比例教学素材。','teacher-efficiency'],['06','试卷讲评PPT','把试卷变成一堂讲评课','识别题目与图形，编排为课堂可直接使用的 16:9 课件。','teacher-efficiency'],['07','错题举一反三','从一道错题扩展一组训练','识别错因并生成同源、变式与迁移练习。','teaching-score'],['08','题卷重排WORD','把任意上传资料完整重排成 Word','完整识别标题、正文、题目、公式、表格与图形，导出可编辑文档。','teacher-efficiency'],['09','AI备课器','从教材资料生成完整教案','组织目标、学情、活动、评价与作业，形成可编辑备课方案。','teacher-efficiency'],['10','AI提分空间评测器','测出最值得投入的提分空间','结合成绩、试卷和学习表现，生成提分空间评测报告。','training-enrollment'],['11','AI丢分诊断器','定位每一次丢分的真正原因','从试卷、作业和错题材料中识别丢分模式与修复方向。','training-enrollment'],['12','错题归因追分器','把错题归因转成可追踪增分路径','分析错题、知识点与学习阶段，生成可执行的追分方案。','training-enrollment'],['13','知识查缺补漏器','绘制知识缺口与补漏地图','从试卷和知识点材料定位薄弱环节，安排补漏优先级。','training-enrollment'],['14','考前抢分清单器','把考前时间换成确定得分点','基于试卷表现生成考前复习清单、风险控制和时间安排。','training-enrollment'],['15','AI题型提分卡','一张卡看懂题型与得分路径','从题目材料提炼题型特征、解题策略、易错点和后续训练。','training-enrollment'],['16','提分行动计划器','把目标分拆成每天的行动','依据当前水平、目标分和可用时间生成阶段化提分计划。','training-enrollment'],['17','AI审题器','把题目条件拆成可执行步骤','提取任务词、限制条件、关键数据和隐藏条件，减少审题漏项。','teaching-score'],['18','AI解题步骤器','用步骤支架带着学生解题','将题目拆成连续提示与检查点，帮助学生形成稳定解题路径。','teaching-score'],['19','AI得分点拆解器','把评分标准拆成可检查得分点','逐项比对学生答案与评分要求，明确已得分、失分和补强动作。','teaching-score'],['20','AI错因判断器','区分知识、方法与审题错误','从学生答案和题目证据判断错因类型，并给出针对性修正建议。','teaching-score'],['21','题感训练提分器','在连续选择与反馈中形成题感','围绕知识点训练判断、方法选择和陷阱识别，沉淀稳定题感。','teaching-score'],['22','试卷变式机','把原题变成分层训练','上传原卷后生成相似题、变式题与综合应用题。','teacher-efficiency'],['24','课文预习单','把教材资料整理成可直接使用的课文预习单','上传教材、试卷或作业，提炼知识地图、重点难点与课前学习任务。','teacher-efficiency'],['25','课堂笔记生成器','把课堂资料整理成结构清晰的复习笔记','汇总教材、板书、试卷和作业，生成可复习、可打印的课堂笔记。','teacher-efficiency'],['26','智批作业机','整班作业一次批完','批量上传学生作业，自动识别得分、评分说明并按批次归档。','teacher-efficiency']];
const groups=[['teacher-efficiency','AI赋能教师提效','把备课、资料和课堂制作变成可复用的工作流。'],['teaching-score','AI赋能教学提分','围绕审题、解题、得分与错因，建立教学提分闭环。'],['training-enrollment','AI赋能教培招生','把评测、诊断和行动计划沉淀为可展示的提分服务。']];
const playbooks={
'17':['任务词','限制条件','关键数据','隐藏条件','干扰信息','作答范围'],
'18':['读题与标注','选择方法','分步计算','规范作答'],
'01':['目标与范围','知识点覆盖','题型与难度分布','生成试卷并检查答案与分值'],
'02':['读取得分与失分证据','按知识点/题型聚合问题','排序最值得投入的增分点','生成七天复习行动表'],
'03':['整理教材章节结构','生成理解讲解与例题','补充分层练习','编排复习清单与可打印讲义'],
'06':['识别题目、图形与考点','为每题安排讲评重点','编排课堂导入/讲解/练习','输出 16:9 课件大纲'],
'07':['定位原题错因','生成同源基础题','生成变式与迁移题','安排由易到难的训练顺序'],
'08':['识别标题、段落和题号','还原公式、表格与图片','校正版式层级','导出可编辑 Word'],
'09':['提取教材目标','分析学情与重难点','安排活动、评价和作业','生成可编辑教案'],
'10':['汇总成绩与试卷证据','计算知识点掌握区间','标注高回报提分空间','形成评测报告'],
'11':['按题目统计丢分','区分知识/方法/审题问题','寻找重复丢分模式','给出修复练习'],
'12':['整理错题与知识点','按阶段归因','把原因转成增分任务','生成可追踪复盘表'],
'13':['扫描试卷知识点','标记薄弱与缺失内容','安排补漏优先级','生成复习地图'],
'14':['识别考前高频得分点','控制失分风险','按剩余时间排程','输出考前清单'],
'15':['识别题型特征','提炼解法与得分路径','列出易错点','生成后续训练建议'],
'16':['输入当前分数与目标分','估算差距与时间','拆成阶段和每日动作','设置检查节点'],
'19':['答题对象','核心结论','关键依据','推理步骤','关键词','格式要求'],
'20':['比对题目与学生答案','判断知识/方法/审题错因','引用证据说明判断','给出纠正练习'],
'21':['选择知识点与题型','连续呈现判断题','即时反馈方法选择','记录陷阱识别表现'],
'22':['抽取原题结构与考点','生成同源题','生成参数/情境变式','生成综合应用题并校验答案'],
'23':['确定主题与知识点','选择版式比例与参考风格','批量生成教辅画面','导出课堂素材'],
'24':['提取课文知识地图','标注重点难点','设计课前任务','输出预习单'],
'25':['汇总教材、板书和作业','按主题重组知识','补充例题与易错提醒','生成复习笔记'],
'26':['识别学生与题目','按批次评分','生成评分说明与错题标签','汇总班级数据']};
window.SPEC_PLAYBOOKS=playbooks;
const fieldConfigs={
'01':['数学','年级、学科、知识点与难度'], '02':['自动识别','试卷或成绩资料'], '03':['自动识别','教材/章节资料'], '06':['自动识别','试卷与图形资料'],
'07':['数学','原题与错题答案'], '08':['自动识别','PDF / Word / 图片'], '09':['自动识别','教材与教学要求'], '10':['自动识别','成绩与试卷资料'],
'11':['自动识别','试卷、作业和错题'], '12':['自动识别','错题与知识点'], '13':['自动识别','试卷与知识点'], '14':['自动识别','试卷与考试时间'],
'15':['自动识别','题目或题型资料'], '16':['自动识别','当前分数与目标'], '17':['数学','题目、试卷或作业'], '18':['自动识别','题目资料'],
'19':['高中语文','题目与学生答案'], '20':['自动识别','题目与学生答案'], '21':['自动识别','知识点与题目'], '22':['自动识别','原卷资料'],
'23':['自动识别','知识库与参考风格'], '24':['自动识别','教材、试卷或作业'], '25':['自动识别','教材、板书和作业'], '26':['自动识别','整班作业资料']};
const scoreProfiles={
  '小学数学':[['答题对象','确认题目要求求什么。','先圈出问题中的未知量。'],['核心结论','给出正确数值并回答题问。','结果带单位并写完整答句。'],['关键条件','提取数量、图形、时间和单位信息。','把题目数据逐一列出。'],['计算步骤','检查列式、运算顺序和进位退位。','按步骤写出算式，避免跳步。'],['公式与单位','检查四则运算、面积体积和单位换算。','统一单位后再计算。'],['格式要求','检查竖式、单位、答句和验算。','完成估算与合理性检查。']],
  '高中数学':[['答题对象','确认求解对象、范围和题目任务。','先写出“求什么”，避免答非所问。'],['核心结论','给出最终数值、关系式或证明结论。','把结论放在答案首句并与题问对应。'],['关键条件','列出定义域、已知量、图形关系和限制条件。','在每个结论后标注使用的条件或定理。'],['推理步骤','检查公式选择、代入、变形和逻辑衔接。','按“条件—公式—计算—结论”补齐跳步。'],['公式与符号','检查函数、方程、不等式、单位和符号书写。','用教材规范符号替换口语化表达。'],['格式要求','检查分点、范围、单位、答句和验算。','按题目要求整理步骤并补完整答句。']],
  '初中数学':[['答题对象','确认未知量与题目要求。','圈出问题中的求解对象。'],['核心结论','写出最终结果并回答题问。','结论必须带单位或范围。'],['关键条件','提取数量关系、图形条件和已知数据。','每一步注明依据。'],['推理步骤','检查列式、计算和推导顺序。','避免只写结果不写过程。'],['公式与符号','检查公式、等号、单位和几何符号。','使用规范公式与符号。'],['格式要求','检查分点、单位、答句和验算。','完成最后的合理性检查。']],
  '高中语文':[['答题对象','明确题目要求分析的对象、范围和任务动词。','答案围绕题干对象展开。'],['核心结论','给出直接回应题问的中心判断。','每个要点先写结论再写依据。'],['关键依据','引用文本内容、人物行为或关键语句。','补充对应的原文证据。'],['推理步骤','建立文本证据到结论的分析链。','按“内容—手法—作用”展开。'],['关键词','使用教材和阅卷可识别的术语。','把口语表达替换为规范概念。'],['格式要求','检查分点、答句和书写规范。','按分值组织要点，避免漏答。']]
};
function scorePointReport(subject, question, answer, total){const profile=scoreProfiles[subject]||scoreProfiles['高中语文'];const q=question||'未提供题目文本，将依据上传资料识别题干。';const a=answer||'未提供学生答案，当前展示评分标准与补强动作。';const math=/数学/.test(subject);const primary=/小学/.test(subject);return profile.map(([title,observation,action],i)=>{let evidence=observation;if(i===0&&q.length>10)evidence+=' 题目已读取，任务词将从题干中提取。';if(i===1&&a.length>10)evidence+=math?' 将核对最终结果与题目要求的量。':' 将核对答案是否直接回应题问。';if(i===2&&math)evidence+=primary?' 重点检查数量、图形、时间和单位信息。':' 重点检查已知条件、定义域、图形关系和公式来源。';if(i===3&&math)evidence+=' 重点检查公式选择、代入过程、变形和验算。';return {title,observation:evidence,action,score:Math.max(1,Math.round(Number(total||12)/profile.length))}})}
const byId=id=>tools.find(t=>t[0]===id);
function home(){app.innerHTML=`<section class="hero"><div class="hero-shade"></div><div class="hero-content"><p class="hero-eyebrow"><span>教师工作的新基础设施</span><b>2026</b></p><h1>AI赋能教师提效、教学提分、教培增长。</h1><div class="hero-actions"><a class="primary-action" href="#workbench">进入教师工作台 ↘</a><a class="text-action" href="#tool/17">开始复刻流程</a></div></div><aside class="hero-index"><span>01</span><span>02</span><span>03</span></aside></section><section class="workbench" id="workbench">${groups.map((g,i)=>`<section class="module-group"><div class="module-group-heading"><div><p class="module-group-kicker">WORKBENCH / 0${i+1}</p><h2>${g[1]}</h2></div><p>${g[2]}</p></div><div class="module-grid">${tools.filter(t=>t[4]===g[0]).map(t=>card(t)).join('')}</div></section>`).join('')}</section>`}
function card(t){return `<a class="module-card" href="#tool/${t[0]}"><div class="module-top"><span class="module-number">MODULE / ${t[0]}</span></div><h3 class="module-title">${t[1]}</h3><p class="module-label">${t[2]}</p><p class="module-description">${t[3]}</p><span class="module-enter">进入工具 <b>↗</b></span></a>`}
function toolPage(t){
  if(window.renderSpecPage&&window.renderSpecPage(t[0]))return;
  if(t[0]==='21') return senseTrainingPage(t);
  if(t[0]==='01') return examGeneratorPage(t);
  if(t[0]==='07') return variationPage(t);
  const isReview=t[0]==='17', isStepper=t[0]==='18', isScore=t[0]==='19';
  const config=fieldConfigs[t[0]]||['自动识别','资料'];
  const subject=isScore?'高中语文':config[0];
  const action=isReview?'开始审题分析':isStepper?'生成分步引导':isScore?'拆解得分点':'生成结果';
  const initialTitle=isReview?'等待上传题目':isStepper?'等待生成解题路径':isScore?'等待生成得分点报告':'等待生成';
  const initialCopy=isReview?'上传题目后，系统会提取任务词、限制条件、关键数据、隐藏条件与干扰信息。':isStepper?'上传一道题目，AI 将生成四步解题路径和完整答案。':isScore?'上传题目和（可选）学生答案后，系统会按六个维度生成评分诊断。':'填写左侧信息后，点击生成。这里会展示可编辑的结构化结果、解题思路与下一步动作。';
  const extraFields={
    '01':'<label>知识点<input name="knowledge" placeholder="例如：二次函数、力与运动"></label><button type="button" class="text-action inline-action" id="addKnowledge">添加知识点</button><div class="knowledge-list"></div><label>难度<select name="difficulty"><option>基础</option><option>中等</option><option>提高</option></select></label><label>题型数量<input name="count" type="number" min="1" max="50" value="10"></label><label>试卷类型<select name="examType"><option>期末考试</option><option>单元测试</option><option>日常练习</option></select></label><label class="check-row"><input type="checkbox" name="includeAnswer"> 显示答案和解析</label>',
    '02':'<label>考试总分<input name="examScore" type="number" min="1" value="100"></label><label>当前得分<input name="currentScore" type="number" min="0" value="0"></label>',
    '10':'<label>当前成绩<input name="currentScore" type="number" min="0" placeholder="例如：72"></label><label>目标成绩<input name="targetScore" type="number" min="0" placeholder="例如：90"></label>',
    '14':'<label>距离考试天数<input name="days" type="number" min="1" value="7"></label><label>每天可用时间（分钟）<input name="minutes" type="number" min="10" value="60"></label>',
    '16':'<label>当前分数<input name="currentScore" type="number" min="0"></label><label>目标分数<input name="targetScore" type="number" min="0"></label><label>每日学习时间（分钟）<input name="minutes" type="number" min="10"></label>',
    '26':'<label>班级名称<input name="className" placeholder="例如：高一（3）班"></label><label class="upload">学生名单（可选）<input type="file" accept=".csv,.xlsx,.xls"><small class="file-status">CSV / Excel</small></label>',
    '20':'<label>题目文本<textarea name="questionText" placeholder="粘贴题目"></textarea><label>学生答案<textarea name="answerText" placeholder="粘贴学生答案"></textarea><label>希望重点判断<select name="errorType"><option>自动判断</option><option>知识错误</option><option>方法错误</option><option>审题错误</option></select></label>',
    '23':'<label>素材主题<input name="theme" placeholder="例如：函数图像"></label><label>画面比例<select name="ratio"><option>16:9</option><option>4:3</option><option>1:1</option><option>9:16</option></select></label>'
  }[t[0]]||'';
  app.innerHTML=`<section class="tool-page"><a class="back" href="#/">← 返回教师工作台</a><div class="tool-hero"><p class="module-group-kicker">MODULE / ${t[0]}</p><h1>${t[1]}</h1><p class="tool-subtitle">${isReview?'先证明读准，再开始解题':isStepper?'从分步理解到完整规范作答':isScore?'看清每一分怎么拿':t[2]}</p><p>${t[3]}</p></div><div class="tool-layout"><form class="tool-form" id="toolForm"><label>学科<select name="subject"><option>${subject}</option><option>小学语文</option><option>小学数学</option><option>小学英语</option><option>初中数学</option><option>初中物理</option><option>高中数学</option><option>高中语文</option><option>数学</option><option>物理</option><option>语文</option><option>英语</option></select></label>${extraFields}${isScore?'<label>题目总分<input name="totalScore" type="number" min="1" max="200" value="12"></label>':''}<label>年级<select name="grade"><option>${isScore?'高中':isReview?'初中二年级':'自动识别'}</option><option>小学</option><option>一年级</option><option>二年级</option><option>三年级</option><option>四年级</option><option>五年级</option><option>六年级</option><option>七年级</option><option>八年级</option><option>九年级</option><option>高中</option></select></label><label class="upload">${isScore?'上传题目':'上传题目、试卷或作业'}<small>输入类型：${config[1]}</small><input type="file" multiple><small class="file-status">点击或拖拽文件到此处 · PDF / Word / PNG / JPG</small></label>${isScore?'<label class="upload">学生答案（可选）<input type="file"><small class="file-status">用于逐项标记已得分、待补充与书写规范</small></label><label>题目文本<textarea name="questionText" placeholder="也可以直接粘贴题目，便于本地分析"></textarea></label><label>学生答案文本（可选）<textarea name="answerText" placeholder="粘贴学生作答内容"></textarea></label>':''}<label>补充说明（可选）<textarea name="notes" maxlength="200" placeholder="例如：来源、章节、题目背景、已知条件补充说明等…"></textarea></label><button class="modal-primary" type="submit">${action}</button><p class="form-message" aria-live="polite"></p></form><article class="result" id="result"><p class="module-group-kicker">${isReview?'审题结果':isStepper?'分步解题路径':isScore?'得分点报告':'OUTPUT'}</p><h2>${initialTitle}</h2><p>${initialCopy}</p></article></div></section>`;
  const form=document.getElementById('toolForm'), result=document.getElementById('result'), message=form.querySelector('.form-message');
  if(t[0]==='01'){const add=form.querySelector('#addKnowledge'), input=form.elements.knowledge, list=form.querySelector('.knowledge-list');add.addEventListener('click',()=>{const v=input.value.trim();if(!v)return;const tag=document.createElement('span');tag.className='knowledge-tag';tag.textContent=v;list.appendChild(tag);input.value='';});}
  const subjectSelect=form.elements.subject, gradeSelect=form.elements.grade;
  subjectSelect?.addEventListener('change',()=>{const value=subjectSelect.value;if(value.includes('小学')) gradeSelect.value='小学';else if(value.includes('初中')) gradeSelect.value='七年级';else if(value.includes('高中')) gradeSelect.value='高中';});
  form.querySelectorAll('input[type=file]').forEach(input=>input.addEventListener('change',()=>{const status=input.parentElement.querySelector('.file-status');if(status) status.textContent=input.files.length?`已选择 ${input.files.length} 个文件：${Array.from(input.files).map(f=>f.name).join('、')}`:'尚未选择文件';}));
  form.addEventListener('submit',e=>{e.preventDefault();message.textContent='';const question=form.elements.questionText?.value.trim()||'';const required={"01":['knowledge'],"10":['currentScore','targetScore'],"16":['currentScore','targetScore','minutes'],"20":['questionText','answerText'],"23":['theme'],"26":['className']}[t[0]]||[];const missing=required.find(name=>!form.elements[name]?.value.trim());if(missing){message.textContent='请先填写全部必填项后再生成。';return;}if(isScore&&(!question&&!form.querySelector('input[type=file]').files.length)){message.textContent='请粘贴题目文本或上传题目文件后再拆解。';return;}const steps=playbooks[t[0]]||['识别输入资料','提取关键信息','生成结构化分析','输出可执行建议'];const report=isScore?scorePointReport(subjectSelect.value,question,form.elements.answerText.value.trim(),form.elements.totalScore.value):null;const errorReport=t[0]==='20'?[['错误类型',`结合题目与答案，优先判断为：${form.elements.errorType.value}。`,'对照错题证据确认错误来源。'],['关键证据','标记答案中出现的条件遗漏、概念混淆或步骤跳跃。','把证据对应到题目条件。'],['修正示范','重新走一遍正确的读题、方法选择与计算流程。','完成同类题并复盘错误。']].map(x=>({title:x[0],observation:x[1],action:x[2]})):null;result.innerHTML=`<p class="module-group-kicker">OUTPUT / READY</p><h2>${t[1]}结果</h2>${(report||errorReport||steps.map(s=>({title:s,observation:'基于上传内容完成'+s+'，并保留可编辑的中间结果与核验提示。',action:'根据结果执行下一步练习。'}))).map((item,i)=>`<div class="result-block"><b>${String(i+1).padStart(2,'0')} ${item.title}${isScore?' · '+(i<2?'已掌握':i===2||i===4?'有待补全':'书写规范'):''}</b><p>评分观察：${item.observation}</p><p>提分动作：${item.action}</p>${isScore?`<small>建议分值：${item.score||'—'} 分 · 作答依据：${form.elements.answerText.value.trim()?'已读取学生答案':'待补充学生答案'}</small>`:''}</div>`).join('')}<button class="text-action" type="button" id="printResult">导出 / 打印结果</button>`;result.querySelector('#printResult').addEventListener('click',()=>window.print());});
}

function examGeneratorPage(t){
  app.innerHTML=`<section class="exam-page"><a class="exam-back" href="#/">← 返回主页</a><div class="exam-shell"><h1>AI出题机</h1><p class="exam-kicker">CYBER EXAM GENERATOR</p><div class="exam-row"><label>科目<select name="subject"><option>数学</option><option>语文</option><option>英语</option><option>物理</option><option>化学</option><option>生物</option><option>历史</option><option>地理</option><option>政治</option></select></label><label>年级<select name="grade"><option>高中一年级</option><option>高中二年级</option><option>高中三年级</option><option>初中一年级</option><option>初中二年级</option><option>初中三年级</option><option>小学</option></select></label></div><div class="exam-rule"></div><div class="knowledge-mode"><button type="button" class="mode-button active">多知识点</button></div><div class="knowledge-add"><select id="knowledgeSelect"><option value="">-- 请选择要添加的知识点 --</option><option>一元二次函数方程和不等式</option><option>函数零点</option><option>函数性质判断</option><option>三角函数</option></select><button type="button" id="addKnowledge">添加</button></div><div class="knowledge-empty" id="knowledgeEmpty">暂时没有添加知识点</div><div class="exam-summary"><div><b id="knowledgeCount">0</b><span>知识点</span></div><div><b id="testCount">0</b><span>考点</span></div><div><b id="questionCount">0</b><span>题目</span></div></div><p class="summary-hint">添加知识点后开始配置</p><div class="exam-rule"></div><h2>试卷设置</h2><div class="exam-setting"><label>试卷类型<select name="examType"><option>随堂小测</option><option>单元测试</option><option>期中考试</option><option>期末考试</option><option>模拟考试</option></select></label><label class="exam-check"><input type="checkbox" name="includeAnswer"> 显示答案和解析</label><label>要求备注<textarea name="notes" placeholder="输入生成题目的额外要求（可不填）"></textarea></label></div><button class="generate-exam" type="button" id="generateExam">生成试卷</button><p class="exam-message" id="examMessage"></p><article class="exam-output" id="examOutput" hidden></article></div></section>`;
  const select=document.getElementById('knowledgeSelect'), add=document.getElementById('addKnowledge'), empty=document.getElementById('knowledgeEmpty'), kc=document.getElementById('knowledgeCount'),tc=document.getElementById('testCount'),qc=document.getElementById('questionCount'),msg=document.getElementById('examMessage'),out=document.getElementById('examOutput'); let chosen=[];
  add.addEventListener('click',()=>{if(!select.value||chosen.includes(select.value))return;chosen.push(select.value);empty.innerHTML=chosen.map((x,i)=>`<span class="exam-tag">${String(i+1).padStart(2,'0')} ${x}<button type="button" data-remove="${i}">×</button></span>`).join('');kc.textContent=chosen.length;tc.textContent=chosen.length*2;qc.textContent=chosen.length*2;empty.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>{chosen.splice(Number(btn.dataset.remove),1);add.click();}));});
  document.getElementById('generateExam').addEventListener('click',()=>{if(!chosen.length){msg.textContent='请先添加至少一个知识点。';return;}out.hidden=false;out.innerHTML=`<h3>试卷参数已就绪</h3><p>科目：${document.querySelector('.exam-shell select[name=subject]').value}　年级：${document.querySelector('.exam-shell select[name=grade]').value}</p><p>知识点：${chosen.join('、')}</p><p>试卷类型：${document.querySelector('.exam-shell select[name=examType]').value}</p>${document.querySelector('input[name=includeAnswer]').checked?'<p>将包含答案和解析。</p>':''}`;msg.textContent='';});
}

function variationPage(t){
  app.innerHTML=`<section class="tool-page variation-page"><a class="back" href="#/">← 返回教师工作台</a><div class="tool-hero"><p class="module-group-kicker">MODULE / 07</p><h1>错题举一反三</h1><p class="tool-subtitle">从一道错题扩展一组训练</p><p>先定位错因，再生成同源、变式与迁移练习。</p></div><div class="tool-layout"><form class="tool-form" id="variationForm"><label>学科<select name="subject"><option>数学</option><option>语文</option><option>英语</option><option>物理</option><option>化学</option></select></label><label>年级<select name="grade"><option>请选择年级</option><option>小学</option><option>初中</option><option>高中</option></select></label><label>原题文本<textarea name="question" placeholder="粘贴做错的原题"></textarea></label><label>学生错答<textarea name="wrongAnswer" placeholder="粘贴学生原来的错误答案"></textarea></label><label>补充说明（可选）<textarea name="notes" placeholder="例如：学生认为哪里不会"></textarea></label><button class="modal-primary" type="submit">生成举一反三训练</button><p class="form-message" aria-live="polite"></p></form><article class="result" id="variationResult"><p class="module-group-kicker">训练结果</p><h2>等待输入错题</h2><p>提交原题和错答后，将生成同源题、变式题、迁移题以及针对性纠错提示。</p></article></div></section>`;
  const form=document.getElementById('variationForm'), result=document.getElementById('variationResult'), msg=form.querySelector('.form-message');
  form.addEventListener('submit',e=>{e.preventDefault();msg.textContent='';if(!form.elements.grade.value||!form.elements.question.value.trim()||!form.elements.wrongAnswer.value.trim()){msg.textContent='请先选择年级，并填写原题和学生错答。';return;}const items=[['错因定位','根据题目条件与错答比对，标记审题、知识或方法问题。'],['同源基础题','保持核心知识点不变，降低计算复杂度，先修复基本步骤。'],['变式训练题','调整数字、条件或问法，检查能否迁移原方法。'],['综合迁移题','加入新情境和多条件，检验完整解题路径。']];result.innerHTML=`<p class="module-group-kicker">${form.elements.subject.value} · ${form.elements.grade.value}</p><h2>举一反三训练包</h2>${items.map((x,i)=>`<div class="result-block"><b>${String(i+1).padStart(2,'0')} ${x[0]}</b><p>${x[1]}</p><small>依据：已读取原题与学生错答，可继续编辑后再次生成。</small></div>`).join('')}<button class="text-action" type="button" id="exportVariation">导出训练包</button>`;result.querySelector('#exportVariation').addEventListener('click',()=>window.print());});
}

function senseTrainingPage(t){
  const grades=[['小学三年级','三年级'],['小学四年级','四年级'],['小学五年级','五年级'],['小学六年级','六年级'],['初一','七年级'],['初二','八年级'],['初三','九年级'],['高一','十年级'],['高二','十一年级'],['高三','十二年级']];
  app.innerHTML=`<section class="tool-page sense-page"><a class="back" href="#/">← 返回教师工作台</a><div class="tool-hero"><p class="module-group-kicker">MODULE / 21</p><h1>题感训练</h1><p class="tool-subtitle">做100道题不如看透10道题</p></div><div class="sense-stats"><div><b>1</b><span>已训练</span></div><div><b>100%</b><span>正确率</span></div><div><b>1</b><span>连续正确</span></div></div><form class="tool-form sense-form" id="senseForm"><section><h2>选择年级</h2><div class="choice-grid grade-grid">${grades.map(g=>`<button type="button" class="choice-card" data-grade="${g[0]}"><b>${g[0]}</b><span>${g[1]}</span></button>`).join('')}</div></section><section class="subject-section" hidden><h2>选择学科</h2><div class="choice-grid subject-grid"><button type="button" class="choice-card" data-subject="语文">语文</button><button type="button" class="choice-card" data-subject="数学">数学</button><button type="button" class="choice-card" data-subject="英语">英语</button><button type="button" class="choice-card" data-subject="物理">物理</button></div></section><section><h2>输入知识点</h2><input name="knowledge" placeholder="输入知识点"><p class="hint">后续题目会围绕这个知识点连续训练。默认快速训练：一次生成10题，完整生成后逐题作答并即时反馈。</p></section><button class="modal-primary" type="submit" disabled>开始训练</button><p class="form-message" aria-live="polite"></p></form><article class="result" id="senseResult"><p class="module-group-kicker">训练区</p><h2>准备开始</h2><p>请先选择年级、学科和知识点。</p></article></section>`;
  const form=document.getElementById('senseForm'), result=document.getElementById('senseResult'), msg=form.querySelector('.form-message'); let selectedGrade='',selectedSubject='';
  form.querySelectorAll('[data-grade]').forEach(btn=>btn.addEventListener('click',()=>{selectedGrade=btn.dataset.grade;form.querySelectorAll('[data-grade]').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');form.querySelector('.subject-section').hidden=false;}));
  form.querySelectorAll('[data-subject]').forEach(btn=>btn.addEventListener('click',()=>{selectedSubject=btn.dataset.subject;form.querySelectorAll('[data-subject]').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');sync();}));
  const sync=()=>{form.querySelector('button[type=submit]').disabled=!(selectedGrade&&selectedSubject&&form.elements.knowledge.value.trim());}; form.elements.knowledge.addEventListener('input',sync);
  form.addEventListener('submit',e=>{e.preventDefault();sync();if(e.submitter.disabled)return;result.innerHTML=`<p class="module-group-kicker">训练进行中 · ${selectedGrade} · ${selectedSubject}</p><h2>第 1 / 10 题</h2><div class="result-block"><b>${form.elements.knowledge.value.trim()}：请选择最合适的解题方向</b><p>先判断题目考查的知识点和条件，再选择方法。</p><button type="button" class="text-action" data-choice="A">A. 直接套用公式</button><button type="button" class="text-action" data-choice="B">B. 先提取已知条件</button><p class="form-message" aria-live="polite"></p></div>`;result.querySelectorAll('[data-choice]').forEach(choice=>choice.addEventListener('click',()=>{result.querySelector('.form-message').textContent=choice.dataset.choice==='B'?'判断正确：先提取条件，再选择方法。':'再看一步：先标出已知条件和任务词。';}));});
}

function route(){if(authDialog?.open)authDialog.close();const m=location.hash.match(/^#tool\/(\d+)/);m?toolPage(byId(m[1])):home()} window.addEventListener('hashchange',route);route();account.onclick=()=>authDialog.showModal();authForm.onsubmit=e=>{e.preventDefault();const name=authForm.username.value.trim()||'本地教师';account.textContent=name+' ⌄';authMessage.textContent='登录成功，本地演示账号已启用。';setTimeout(()=>authDialog.close(),500)};

})();
